# Generated by Django 4.1.6 on 2023-02-02 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('participants', models.IntegerField()),
                ('price', models.FloatField()),
                ('link', models.CharField(max_length=500, null=True)),
                ('key', models.IntegerField()),
                ('accessibility', models.FloatField()),
                ('use_it', models.BooleanField(default=True)),
                ('done', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
